### PR TITLE
separate set_images in function + doc

### PR DESCRIPTION
**Pull request by DrAnaximandre**
This PR aims at modifying set_images.

It has been reworked and separated in smaller functions, so that the main function is easier to maintain.
However it has not been tested on augmented data (that is the one with a `task` label).

@tfunck can you test the code on both augmented and non-augmented data before merging ?  (I did the tests on non-augmented data and it worked but I'd prefer if you'd double check).

### CODE REVIEW

**Comment by nbelakovski** [comment]
these changes look great, things are super broken out.

**Comment by DrAnaximandre** [comment]
Also note that the random attribution has changed.

Previously, the code stated:
` nfolds=np.random.multinomial(nSubjects,ratios)`, meaning that the number of test/train subject was *the realisation of* a random variable. That meant that a run from the code could give a 50/50 test train, and another run could give a 90/10. 

Now the proposed code is:
` i_train = np.random.choice( np.arange(nSubjects), int(ratios[0] * nSubjects))`
meaning we truncate the number of subject times the first value of ratio (usually 0.7), and we pick that many indices in a range of nSubjects. As a result, the ratio train/test will always be the same on several runs (given that the number of subjects is the same) - that is around usually 70/30.

**Comment by tfunck** [comment]
Very nice! Great comments, I'll start commenting the rest of the code like that. 

Something to note is that all of the data should really have the "task-<>" format. This is because it makes things a lot easier if the code is compatible with the Brain Imaging Data Specification (BIDS, http://bids.neuroimaging.io/). I should have formatted it this way from the beginning. To add the "task-<>" to your code you can run the following without the 'echo' at the end:
cd data/
find . -name sub*.mnc -exec bash -c "echo {} | sed 's#\(sub-[0-9][0-9]\)#\1_task-01#2' | xargs  echo mv {}" \; 

I'll add the script to augment the data so that you guys can use it as well.

**Review by tfunck — APPROVED** [review]

**Comment by tfunck** [comment]
I got an error on line 158:
    out = pd.DataFrame(columns=dfd[dfd.keys()[0]].columns)
TypeError: 'dict_keys' object does not support indexing

so I changed it to

    out = pd.DataFrame(columns=dfd[list(dfd.keys())[0]].columns)

Also tested on the augmented set and it works fine

**Comment by DrAnaximandre** [comment]
Ah you are right, I was running on python 2.something, my bad.

**Pull request merged**
